// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1bvA1jDyVOZqCVVDE1Ye3k3sgI9Ycrw',
    appId: '1:753537962004:web:8cb3d3f12bcda3905a5701',
    messagingSenderId: '753537962004',
    projectId: 'chat-app-ff4f6',
    authDomain: 'chat-app-ff4f6.firebaseapp.com',
    storageBucket: 'chat-app-ff4f6.appspot.com',
    measurementId: 'G-H5GEKHVKMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo4leAC6LB6ZEZNA4v_VY7cEDiEqdH93E',
    appId: '1:753537962004:android:e362c91f7d40aa865a5701',
    messagingSenderId: '753537962004',
    projectId: 'chat-app-ff4f6',
    storageBucket: 'chat-app-ff4f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ0YOJkoeJem3pIwuEZ1Yw_e3vWQsbpIc',
    appId: '1:753537962004:ios:38f0612b02a49a7b5a5701',
    messagingSenderId: '753537962004',
    projectId: 'chat-app-ff4f6',
    storageBucket: 'chat-app-ff4f6.appspot.com',
    iosClientId: '753537962004-02mol5fnpi5sec1rmrmhvbgfr8g1lad2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ0YOJkoeJem3pIwuEZ1Yw_e3vWQsbpIc',
    appId: '1:753537962004:ios:11ae96b75fc96d415a5701',
    messagingSenderId: '753537962004',
    projectId: 'chat-app-ff4f6',
    storageBucket: 'chat-app-ff4f6.appspot.com',
    iosClientId: '753537962004-g79uffpa8as7b81ogra8hbp9iigotdu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
